#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

export APP_HOME=/opt/app

start() {
  java -jar $APP_HOME/springmedia-assignment.jar --spring.config.location=$APP_HOME/application.properties,$APP_HOME/remote-services.yaml > $APP_HOME/springmedia-assignment.log   
}

stop() {
    # kill java
    PID=$(/bin/pidof java)
    if [ $? -eq 0 ]; then
      kill -9 $PID
    fi
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       PID=$(/bin/pidof java)
       if [ $? -eq 0 ]; then
         echo "app is running."
       else
         echo "app is not running"
       fi

      ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
