version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    networks:
      ia-net:
       ipv4_address: 173.20.0.3
    container_name: app 
    hostname: app.spring-media.com
    command :
      - "/bin/bash"
      - "-c"
      - "service app_service start"
    ports:
    - "8090:8090"
    #volumes:
    #- "${HOME}/extconfig:/opt/app/"
networks:
  ia-net:
    name: spring-media.com
    driver: bridge
    ipam:
      config:
        - subnet: 173.20.0.0/16  
